### ISSUE TITLE
Needs administrator

### ISSUE THREAD

**Issue by KTibow** [RRR06/QustodioBypass#1]
The scripts need admin. It'd be nice if there was a way to trick Qustodio, without requiring admin.

**Comment by thegu5** [comment]
Maybe try safe booting then deleting all qustodio files? Or whatever the thing is that opens an admin command prompt during startup

**Comment by KTibow** [comment]
bro you know im using linux rn lol

**Comment by jaevibing** [comment]
@KTibow Qustodio has no linux binaries. Is Qustodio installed on a separate windows machine or an Android/iPhone?

**Comment by KTibow** [comment]
@jack-debug by this i mean i switched to linux in order to get rid of qustodio

**Comment by RRR06** [comment]
MacOS and Linux stem from Unix, my philosophy is if you have physical access to a computer, there's always a way to gain admin access (aka. root/superuser). In MacOS and Linux this is done by booting into a recovery image (recovery mode on MacOS) and editing the /etc/sudoers file. If you're interested, check out my [website](https://robigan.com/contact) for contact info
