### ISSUE TITLE
I get an error when trying to run on bug sur

### ISSUE THREAD

**Issue by RealYusufIsmail** [RRR06/QustodioBypass#2]
config.sh: line 2: [close: command not found
config.sh: line 13: [close: command not found

**Comment by robigan** [comment]
Oh, the project is kinda dead, and I recommend joining the discord anyways
(Btw am answering from my main, @RRR06 is my alt acc)

**Comment by ohStrqfed** [comment]
dude are you seriously gonna leave me hanging I really wanna get rid of this

**Comment by RRR06** [comment]
Did you join the Discord?

- Robigan
